name: Build Xiaomi 8
on:
  workflow_dispatch:
  schedule:
      # Run once at 12:00 on Saturday.. See http://crontab.guru
      - cron: '00 12 * * 6'
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-latest
    #env:
    #  CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
    #  CCACHE_NOHASHDIR: "true"
    #  CCACHE_MAXSIZE: "2G"
    #  CCACHE_HARDLINK: "true"
      
    steps:
    - name: Set swap to 10G 将swap设置为10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install binutils make python2 libssl-dev flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y
        sudo apt-get clean
        git clone https://github.com/13231178/proton-clang.git
        
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT
    #bash build_kernel_byd_git_clang.sh
    - name: Build Kernel
      run: |
       sudo ln -sf /usr/bin/python2.7 /usr/bin/python
       bash synckernelsu_all.sh
       export PATH=$PATH:$(pwd)/proton-clang/bin
       export CC=clang
       export CLANG_TRIPLE=aarch64-linux-gnu-
       export CROSS_COMPILE=aarch64-linux-gnu-
       export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
       export CONFIG_BUILD_ARM64_DT_OVERLAY=y
       export ARCH=arm64
       export DTC_EXT=dtc
       mkdir out
       make ARCH=arm64 O=out CC=clang generic_xiaomi_sdm845_dipper_ksu_defconfig
       make ARCH=arm64 O=out CC=clang -j$(nproc --all) 

    - name: Upload BYD-Kernel
      uses: actions/upload-artifact@v3
      with:
        name: Mi8_sdm845_Kernel-${{ steps.get_time.outputs.TIME }}
        path: "out/arch/arm64/boot/Image*"
